# Generated by Django 5.1.6 on 2025-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('cholesterol', models.PositiveIntegerField(blank=True, null=True)),
                ('glucose', models.PositiveIntegerField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
